general:
  # negative is all
  gpus:              -1
  threads:           1
  # size to load in memory at a time (width x height x bands x bit-width x chunk-size^2)
  block_size_mb:     1
  # number of different images to interleave at a time when loading
  interleave_images: 5
  # ratio of tile width and height when loading images
  tile_ratio:        5.0
  cache:
    # default is OS-specific, in Linux, ~/.cache/delta
    dir:              ~
    limit:            8

images:
  type:             tiff
  # preprocess the images when loading (i.e., scaling)
  preprocess:       true
  nodata_value:     ~
  directory:        ~/nasa/delta/bin/landsat/data_no_ground_truth
  extension:        .tif
  file_list:        ~
  files:            ~

labels:
  type:             tiff
  preprocess:       false
  nodata_value:     ~
  directory:        ~/nasa/delta/bin/landsat/labels
  extension:        .tif
  file_list:        ~
  files:            ~

network:
  chunk_size:      16
  output_size:     8
  classes:         2
  model:
    yaml_file:     networks/convpool.yaml
    params:        ~
    layers:        ~

train:
  chunk_stride:    1
  batch_size:      100
  steps:           10 # number of batches to train on (or ~ for all)
  epochs:          5
  loss_function:   mse
  metrics:
  experiment_name: debug # used in tracking tools
  optimizer:       adam
  validation:
    steps:         20
    # if true, skips the first steps from the training set to use for validation instead
    from_training: true
    # otherwise uses the first samples from this dataset:
    images:
      type:        tiff
      preprocess:  true
      nodata_value: ~
      directory:   ~
      extension:   ~
      file_list:   ~
      files:       ~
    labels:
      type:        tiff
      preprocess:  true
      nodata_value: ~
      directory:   ~
      extension:   ~
      file_list:   ~
      files:       ~
 
mlflow:
  # default to ~/.local/share/delta/mlflow
  enabled:        true
  uri:            ~
  # rate in batches to save metrics
  frequency:      10000
  # rate in batches to save model checkpoints
  checkpoints:
    frequency:     10000
    save_latest:   true
tensorboard:
  enabled:        false
  frequency:      1000
  # default to ~/.local/share/delta/tensorboard
  dir:            ~
