layers:
  - Input:
      shape: in_shape
  - Flatten:
      input_shape: in_shape
  - Dense:
      units: 300
      activation: relu
  - Dense:
      units: in_dims
      activation: relu
  - Reshape:
      target_shape: in_shape
