layers:
  - InputLayer:
      input_shape: in_shape
  - Conv2D:
      filters: 300
      kernel_size: [3, 3]
      activation: relu
      padding: same
  - MaxPooling2D:
      pool_size: [2, 2]
  - Conv2D:
      filters: 150
      kernel_size: [3, 3]
      activation: relu
      padding: same
  - MaxPooling2D:
      pool_size: [2, 2]
  - Conv2D:
      filters: 75
      kernel_size: [3, 3]
      activation: relu
      padding: same
  - UpSampling2D:
      size: [2, 2]
  - Conv2D:
      filters: 150
      kernel_size: [3, 3]
      activation: relu
      padding: same
  - UpSampling2D:
      size: [2, 2]
  - Conv2D:
      filters: num_bands
      kernel_size: [3, 3]
      activation: relu
      padding: same
