params:
  dropout_rate: 0.3
  num_filters: 64
  out_dims: 27 # 3 * 3 * 3
layers:
  - Input:
      shape: [5, 5, num_bands]
  - Conv2D:
       filters: num_filters
       kernel_size: [5, 5]
       activation: relu
       padding: same
  - Dropout:
       rate: dropout_rate
  - MaxPooling2D:
       pool_size: [2, 2]
  - Conv2D:
       filters: num_filters
       kernel_size: [3, 3]
       activation: relu
       padding: same
  - Dropout:
       rate: dropout_rate
  - MaxPooling2D:
       pool_size: [2, 2]
  - Flatten:
  - Dense:
       units: out_dims
       activation: linear
  - Reshape:
       target_shape: [3, 3, num_classes]
  - Softmax:
       axis: 3
