layers:
  - Input:
      shape: [~, ~, num_bands]
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_1_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_1_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - MaxPooling2D:
      pool_size: [2, 2]
      strides: 2
      name: pooling_1
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_2_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_2_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - MaxPooling2D:
      pool_size: [2, 2]
      strides: 2
      name: pooling_2
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_3_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_3_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_3_3
  - BatchNormalization:
  - Activation:
      activation: relu
  - MaxPooling2D:
      pool_size: [2, 2]
      strides: 2
      name: pooling_3
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_4_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_4_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_4_3
  - BatchNormalization:
  - Activation:
      activation: relu
  - MaxPooling2D:
      pool_size: [2, 2]
      strides: 2
      name: pooling_4
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_5_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_5_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_5_3
  - BatchNormalization:
  - Activation:
      activation: relu
  - MaxPooling2D:
      pool_size: [2, 2]
      strides: 2
      name: pooling_5
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_1
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_1_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_1
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_1_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_1_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_1_3
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_2
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_2_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_2_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_2_3
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_3
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_3_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_3_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_3_3
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_4
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_4_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_4_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_5
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_5_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_5_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: num_bands
      kernel_size: [7, 7]
      activation: relu
      padding: same
